// <auto-generated />
namespace NETDatingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Hej20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Hej20));
        
        string IMigrationMetadata.Id
        {
            get { return "201901040944141_Hej2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
